version: '3.7'


services:

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-t1
    ports:
      - "9411:9411"

  prometheus:
    image: prom/prometheus
    container_name: prometheus-t1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana-t1
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_config:/etc/grafana
    networks:
      - monitor-net



volumes:
  grafana_data:
  grafana_config:



networks:
  monitor-net:
    driver: bridge