global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

rule_files:
#  - "alert.rules.yml"
#  - "rules.yml"

scrape_configs:
  - job_name: 'listen-to-music'
    scrape_interval: 2s
    metrics_path: '/listen-to-music/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:9010' ]
