spring:
  application:
    name: listen-to-music
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
  datasource:
    url: 'jdbc:postgresql://localhost:5432/listen-to-music'
    username: postgres
    password: vw@22*CF!11
  data:
    redis:
      host: localhost
      port: 6379
      database: 3
application:
  security:
    jwt:
      secret-key: C2487167B120D32EDEB1C631FCDBF71814417EDFAD419D08C0697F37501675BB
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans




